-- Supabase 'drivers' Tablosu Oluşturma SQL Komutu

CREATE TABLE IF NOT EXISTS public.drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver TEXT NOT NULL,
    plate TEXT,
    phone TEXT NOT NULL,
    entry TEXT DEFAULT '*',
    exit TEXT DEFAULT '*',
    ramp TEXT DEFAULT '*',
    note TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS Politikaları (Tüm okuma ve yazma işlemlerine izin ver)
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations for public" ON public.drivers FOR ALL USING (true) WITH CHECK (true);
